services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/data.sql:/docker-entrypoint-initdb.d/data.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -ppassword -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sports-center
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SERVER_PORT: 8282
    ports:
      - "8282:8282"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "8080:80"


volumes:
  db_data: